// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace GMSBlog.Web.Controllers {
    [CompilerGenerated]
    public partial class AccountController {
        public AccountController() { }

        protected AccountController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult LogOut() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.LogOut);
        }

        public AccountController Actions { get { return MVC.Account; } }

        public readonly string Area = "";
        public readonly string Name = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        public ActionNamesClass ActionNames { get { return s_actions; } }
        public class ActionNamesClass {
            public readonly string LogOn = "LogOn";
            public readonly string LogOut = "LogOut";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string LogOn = "~/Views/Account/LogOn.aspx";
        }
    }

    [CompilerGenerated]
    public class T4MVC_AccountController: GMSBlog.Web.Controllers.AccountController {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult LogOn() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOn);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOn(string username, string password, string returnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOn);
            callInfo.RouteValueDictionary.Add("username", username);
            callInfo.RouteValueDictionary.Add("password", password);
            callInfo.RouteValueDictionary.Add("returnUrl", returnUrl);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult LogOut(string returnUrl) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.LogOut);
            callInfo.RouteValueDictionary.Add("returnUrl", returnUrl);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
