// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace GMSBlog.Web.Controllers {
    [CompilerGenerated]
    public partial class AdminController {
        public AdminController() { }

        protected AdminController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult DeleteCategory() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeleteCategory);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Posts() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Posts);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult DeletePost() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.DeletePost);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult EditPost() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.EditPost);
        }
        [NonAction]
        public System.Web.Mvc.PartialViewResult GetPostPreview() {
            return new T4MVC_PartialViewResult(Area, Name, ActionNames.GetPostPreview);
        }

        public AdminController Actions { get { return MVC.Admin; } }

        public readonly string Area = "";
        public readonly string Name = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        public ActionNamesClass ActionNames { get { return s_actions; } }
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Categories = "Categories";
            public readonly string AddCategoryLink = "AddCategoryLink";
            public readonly string AddCategory = "AddCategory";
            public readonly string DeleteCategory = "DeleteCategory";
            public readonly string Posts = "Posts";
            public readonly string AddPost = "AddPost";
            public readonly string DeletePost = "DeletePost";
            public readonly string EditPost = "EditPost";
            public readonly string GetPostPreview = "GetPostPreview";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string AddCategory = "~/Views/Admin/AddCategory.ascx";
            public readonly string AddCategoryLink = "~/Views/Admin/AddCategoryLink.ascx";
            public readonly string AddPost = "~/Views/Admin/AddPost.aspx";
            public readonly string Categories = "~/Views/Admin/Categories.aspx";
            public readonly string GetPostPreview = "~/Views/Admin/GetPostPreview.ascx";
            public readonly string Index = "~/Views/Admin/Index.aspx";
            public readonly string Posts = "~/Views/Admin/Posts.aspx";
        }
    }

    [CompilerGenerated]
    public class T4MVC_AdminController: GMSBlog.Web.Controllers.AdminController {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Categories() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Categories);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCategoryLink() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCategoryLink);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCategory() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCategory);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddCategory(GMSBlog.Model.Entities.Category category) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddCategory);
            callInfo.RouteValueDictionary.Add("category", category);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeleteCategory(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeleteCategory);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Posts(int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Posts);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddPost() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddPost);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddPost(GMSBlog.Model.Entities.Post post, System.Web.Mvc.FormCollection collection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddPost);
            callInfo.RouteValueDictionary.Add("post", post);
            callInfo.RouteValueDictionary.Add("collection", collection);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult DeletePost(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.DeletePost);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditPost(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditPost);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditPost(GMSBlog.Model.Entities.Post post, System.Web.Mvc.FormCollection collection) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.EditPost);
            callInfo.RouteValueDictionary.Add("post", post);
            callInfo.RouteValueDictionary.Add("collection", collection);
            return callInfo;
        }

        public override System.Web.Mvc.PartialViewResult GetPostPreview(string previewText) {
            var callInfo = new T4MVC_PartialViewResult(Area, Name, ActionNames.GetPostPreview);
            callInfo.RouteValueDictionary.Add("previewText", previewText);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
