// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace GMSBlog.Web.Controllers {
    [CompilerGenerated]
    public partial class HomeController {
        public HomeController() { }

        protected HomeController(Dummy d) { }

        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = (IT4MVCActionResult)result;
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        public System.Web.Mvc.ActionResult Index() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Post() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Post);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult PostByName() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.PostByName);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult Category() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Category);
        }
        [NonAction]
        public System.Web.Mvc.ActionResult AddComment() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AddComment);
        }

        public HomeController Actions { get { return MVC.Home; } }

        public readonly string Area = "";
        public readonly string Name = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        public ActionNamesClass ActionNames { get { return s_actions; } }
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Post = "Post";
            public readonly string PostByName = "PostByName";
            public readonly string Category = "Category";
            public readonly string About = "About";
            public readonly string AddComment = "AddComment";
        }


        static readonly ViewNames s_views = new ViewNames();
        public ViewNames Views { get { return s_views; } }
        public class ViewNames {
            public readonly string About = "~/Views/Home/About.aspx";
            public readonly string AddComment = "~/Views/Home/AddComment.ascx";
            public readonly string BottomSection = "~/Views/Home/BottomSection.ascx";
            public readonly string Category = "~/Views/Home/Category.aspx";
            public readonly string Comment = "~/Views/Home/Comment.ascx";
            public readonly string Index = "~/Views/Home/Index.aspx";
            public readonly string Post = "~/Views/Home/Post.aspx";
            public readonly string Summary = "~/Views/Home/Summary.ascx";
        }
    }

    [CompilerGenerated]
    public class T4MVC_HomeController: GMSBlog.Web.Controllers.HomeController {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(int? page) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            callInfo.RouteValueDictionary.Add("page", page);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Post(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Post);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult PostByName(string title, int year, int month, int day) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.PostByName);
            callInfo.RouteValueDictionary.Add("title", title);
            callInfo.RouteValueDictionary.Add("year", year);
            callInfo.RouteValueDictionary.Add("month", month);
            callInfo.RouteValueDictionary.Add("day", day);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Category(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Category);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult About() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.About);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddComment(int postId, GMSBlog.Model.Entities.Comment comment) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddComment);
            callInfo.RouteValueDictionary.Add("postId", postId);
            callInfo.RouteValueDictionary.Add("comment", comment);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
